export LANG=$LANG
export JAVA_HOME=$JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH
export CLASSPATH=$JAVA_HOME/lib:.:$CLASSPATH

if [ "$BIN_NAME" == "" ]; then
	BIN_NAME=bin
fi

if [ "$APP_SERVICE_NAME" != "" ]; then
	RUN_DIR_NAME=$APP_SERVICE_NAME
	CONFIG_RUN_DIR_NAME=$APP_SERVICE_NAME
else
	CONFIG_RUN_DIR_NAME=$APP_NAME
fi
RUN_DIR_NAME=$RUN_DIR_NAME-$VERSION_NAME

if [ "$SPEC_MAIN_CLASS" != "" ]; then
	MAIN_CLASS=$SPEC_MAIN_CLASS
fi

CONFIG_HOME=$USER_HOME/$RELATIVE_CONFIG_HOME
if [ "$CONFIG_APP_NAME" == "" ]; then
	CONFIG_APP_NAME=$APP_NAME
fi
CONFIG_APP_HOME=$CONFIG_HOME/$CONFIG_APP_NAME

if [ "$CONFIG_APP_COMMON_NAME" != "" ]; then
	CONFIG_APP_COMMON_HOME=$CONFIG_HOME/$CONFIG_RUN_DIR_NAME/$CONFIG_APP_COMMON_NAME
fi

APP_RUN_HOME=$APP_HOME/$RUN_DIR_NAME
#LOG_APP_HOME=$LOG_HOME/$APP_NAME
LOG_APP_HOME=$LOG_HOME

RUN_COMMAND="java $JAVA_OPTS -Dappname=$APP_NAME -Dfile.encoding=$CHARSET $MAIN_CLASS $1 $2 $CONSOLE_PORT"